config/routes.rb
Rails.application.routes.draw do
  root "events#index"

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, only: :show
  resources :comments
  resources :events do
    member do
      get 'enroll'
      get 'cancel'
      get 'invitation'
      get 'invite'
      get 'decline'
      get 'accept'
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/Invitation.rb
class Invitation < ApplicationRecord
  belongs_to :event, class_name: 'Event'
  belongs_to :invitee, class_name: 'User'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true
  
  belongs_to :user

end

app/models/event.rb
class DateValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value.present? && value >= Date.today
      record.errors.add attribute, "You can't create an event in the past!"
    end
  end
end

class Event < ApplicationRecord
  include ActiveModel::Validations

  validates :title, presence: true
  validates :description, presence: true
  validates :date, presence: true, date: true


  scope :past, -> { where("date < ?", Date.today) }
  scope :upcoming, -> { where("date >= ?", Date.today) }

  belongs_to :creator, class_name: 'User', foreign_key: :creator_id
  has_many :attendances, foreign_key: :attended_event_id, dependent: :destroy
  has_many :attendees, through: :attendances, dependent: :destroy
  has_many :invitations, dependent: :destroy
  has_many :invitees, through: :invitations, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, foreign_key: :creator_id, dependent: :destroy
  has_many :attendances, foreign_key: :attendee_id, dependent: :destroy
  has_many :attended_events, through: :attendances
  has_many :invitations, foreign_key: :invitee_id, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index 
    @comments = Comment.all
  end

  def new
    @comment = Comments.build
  end

  def create
    @event = Event.find(params[:comment][:event_id])
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      redirect_to @event
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to event_path(@comment.event_id)
  end
  
  private
  def comment_params
    params.require(:comment).permit(:body, :event_id, :user_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /events or /events.json
  def index
    @events = Event.all
    
    if user_signed_in?
      @invitations = Invitation.where(invitee_id: current_user.id)
    end
  end

  # GET /events/1 or /events/1.json
  def show
    @comment = Comment.new
  end

  # GET /events/new
  def new
    @event = current_user.events.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def enroll  
    @event = Event.find(params[:id])
    if !@event.attendees.include?(current_user)
      @event.attendees << current_user
    end
    inv = Invitation.where(event_id: @event.id).and(Invitation.where(invitee_id: current_user.id)).first
    if inv
      inv.destroy
    end
    redirect_to @event
  end

  def accept  
    @event = Event.find(params[:id])
    if !@event.attendees.include?(current_user)
      @event.attendees << current_user
    end
    inv = Invitation.where(event_id: @event.id).and(Invitation.where(invitee_id: current_user.id)).first
    inv.destroy
    redirect_to root_path
  end

  def decline  
    invitation = Invitation.find(params[:id])
    invitation.destroy
    redirect_to root_path
  end

  def cancel  
    @event = Event.find(params[:id])
    @event.attendees.delete(current_user)
    redirect_to @event
  end

  def invitation
    @event = Event.find(params[:id])
    @users = User.all
  end

  def invite
    @event = Event.find(params[:event_id])
    @user = User.find(params[:user_id])
    invitation = Invitation.new(event_id: @event.id, invitee_id: @user.id)
    if invitation.save
      flash[:notice] = "Invitation sent!"
      redirect_to invitation_event_path(@event)
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :date, :description)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  private
    def user_params
      params.require(:user).permit(:id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_comment_form.html.erb
<%= form_with model: @comment do |form| %>
  <div class="block">
    <%= form.text_area :body, placeholder: "Type your comment here...", class: "textarea", autofocus: true %>
    <% @comment.errors.full_messages_for(:body).each do |message| %>
      <p><%= message %></p>
    <% end %>
    <%= form.hidden_field :event_id, :value => params[:id] %>
  </div>
  
  <div>
    <%= form.submit value="Submit Comment", class: "button is-primary" %>
  </div>
<% end %>

app/views/events/_form.html.erb
<%= form_with model: event do |form| %>
  <div class="block">
    <%= form.label :title %>
    <%= form.text_field :title, placeholder: "Your event's title", class: "input", autofocus: true%>
    <% event.errors.full_messages_for(:title).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>

  <div class="block">
    <%= form.label :description %>
    <%= form.text_area :description, placeholder: "Details of event...", class: "textarea "%>
    <% event.errors.full_messages_for(:description).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>

  <div class="block">
  <%= form.label :date %>
  <%= form.text_field :date, type: :date, class: "input" %>
  <% event.errors.full_messages_for(:date).each do |message| %>
  <p><%= message %></p>
    <% end %>
  </div>

  
  <div>
  <% if @event.id %>
    <%= form.submit value="Confirm Changes", class: "button is-primary" %>
  <% else %>
    <%= form.submit value="Create", class: "button is-primary" %>
  <% end %>
  </div>
<% end %>

app/views/events/_main_feed.html.erb
<div class="title is-3">Upcoming Events</div>
    </div>
  </div>
  <div class="level-right">
    <div class="level-item">
      <% if user_signed_in? %>
        <%= link_to "New Event", new_event_path, class: "button is-success" %><br />
      <% end %>
    </div>
  </div>
</div>
<% @events.upcoming.order(:date).each do |e| %>
  <% if e.date >= Date.today %>
    <div class="box">
      <div class="level">
        <div class="level-left">
          <div class="level-item">
            <strong class="title is-4"><%= link_to e.title, e %></strong>
          </div>
        </div>
        <div class="level-right">
          <div class="level-item">
            <span class="icon"><i class="fas fa-calendar-alt"></i></span>
            <%= e.date %>
          </div>
          <% if current_user == e.creator %>
          <div class="level-item">
            <%= link_to e, method: :delete, data: { confirm: "Are you sure?" } do %>
              <span class="icon"><i class="fas fa-trash-alt is-danger"></i></span>
            <% end %>
          </div>
          <% end %>
        </div>
      </div>
      <div class="block">
        <p>
        <span class="icon"><i class="fas fa-laptop-house"></i></span>
          Hosted by <%= link_to "@" + e.creator.username, e.creator %>
        </p>
        <p>
          <% if e.attendees.count == 0 %>
            <span class="icon"><i class="fas fa-user-alt-slash"></i></span>
            <%= e.attendees.count %> participant
          <% elsif e.attendees.count == 1 %>
            <span class="icon"><i class="fas fa-user-alt"></i></span>
            <%= e.attendees.count %> participant
          <% elsif e.attendees.count == 2 %>
            <span class="icon"><i class="fas fa-user-friends"></i></span>
            <%= e.attendees.count %> participants
          <% else %>
            <span class="icon"><i class="fas fa-users"></i></span>
            <%= e.attendees.count %> participants
          <% end %>
        </p>
        <p>
          <% if e.comments.count == 0 %>
            <span class="icon"><i class="fas fa-comment-slash"></i></span>
            <%= e.comments.count %> comment
          <% elsif e.comments.count == 1 %>
            <span class="icon"><i class="fas fa-comment"></i></span>
            <%= e.comments.count %> comment
          <% else %>
            <span class="icon"><i class="fas fa-comments"></i></span>
            <%= e.comments.count %> comments
          <% end %>
        </p>
      </div>
      
    </div>
  <% end %>
<% end %>

app/views/events/_personal_feed.erb
<h1 class="title is-3">
  <%= link_to current_user.name, current_user %>
</h1>
<div class="title is-5">
  Hosted events:
</div>
<% current_user.events.upcoming.order(:date).each do |event| %>
  <div class="block">
    <span class="icon"><i class="fas fa-calendar-alt"></i></span>
    <%= event.date %> - <%= link_to event.title, event %>
  </div>
<% end %>
<div class="title is-5">
  Attended events:
</div>
<% Event.all.upcoming.order(:date).each do |event|%>
  <% if event.attendees.include?(current_user) %>
    <div class="block">
      <span class="icon"><i class="fas fa-calendar-alt"></i></span>
      <%= event.date %> - <%= link_to event.title, event %>
    </div>
  <% end %>
<% end %>

app/views/events/_profile_feed.erb
<h1 class="title is-3">
  <%= link_to current_user.name, current_user %>
</h1>
<% if !@invitations.empty? %>
  <div class="title is-5">
    <span class="icon"><i class="fas fa-user-plus"></i></span> Incoming invitations
  </div>
  
  <% @invitations.each do |invitation| %>
    <div class="box invitation">
      <div class="level">
        <div class="level-left">
          <div class="level-item">
            <p>
              <%= link_to invitation.event.title, invitation.event %>
            </p>
          </div>
        </div>
        <div class="level-right">
          <div class="level-item">
            <%= link_to decline_event_path(invitation) do %>
              <i class="far fa-times-circle"></i>
            <% end %>
          </div>
        </div>
      </div>
      <p>by <%= invitation.event.creator.name %> </p>
      <br />
      <div class="level">
        <div class="level-item has-centered-text">
          <div class="field is-grouped">
            <div class="control">
              <%= link_to "Accept", accept_event_path(invitation.event.id), class: "button is-success" %>
            </div>
            <div class="control">
              <%= link_to "Decline", decline_event_path(invitation), class: "button is-danger" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

<div class="title is-5">
  <span class="icon"><i class="fas fa-house-user"></i></span> Hosted events
</div>
<% current_user.events.upcoming.order(:date).each do |event| %>
  <div class="block">
    <span class="icon"><i class="far fa-calendar-alt"></i></span>
    <%= event.date %> - <%= link_to event.title, event %>
  </div>
<% end %>

<div class="title is-5">
  <span class="icon"><i class="fas fa-walking"></i></span>Events to attend
</div>
<% Event.all.upcoming.order(:date).each do |event|%>
  <% if event.attendees.include?(current_user) %>
    <div class="block">
      <span class="icon"><i class="far fa-calendar-check"></i></span>
      <%= event.date %> - <%= link_to event.title, event %>
    </div>
  <% end %>
<% end %>

app/views/events/_users_feed.html.erb
<div class="title is-3">
  Registered Users
</div>
<% User.all.order(:name).each do |user| %>
  <div class="block">
    <span class="icon"><i class="fas fa-user-alt"></i></span>
    <%= link_to "@" + user.username, user %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Edit Event</h1>
					<%= render 'form', event: @event %>
			</div>
		</div>
	</div>
</div>

app/views/events/index.html.erb
<div class="section">
  <div class="container">
    <div class="columns">

      <%# Profile box - Left%>
      <div class="column is-one-quarter">
        <% if user_signed_in? %>
          <div class="box">
            <%= render 'profile_feed' %>
          </div>
        <% end %>
      </div>

      <%# Main feed %>
      <div class="column is-half">
        <div class="level">
          <div class="level-left">
            <div class="level-item">
              
        <%= render 'main_feed' %>
      </div>

      <div class="column is-one-quarter">
        <% if user_signed_in? %>
          <div class="box">
            <%= render 'users_feed' %>
          </div>
        <% end %>
      </div>


  </div>
</div>

app/views/events/invitation.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        <div class="box">

          <div class="level">
            <div class="level-left">
              <div class="level-item">
                <h1 class="title is-4"><%= @event.title %></h1>
              </div>
            </div>
            <div class="level-right">
                <div class="level-item">
                  <%= link_to 'Back to Event', event_path, class: "button is-info" %>
                </div>
            </div>
          </div>
          <% @users.order(:name).each do |user| %>
            <% if @event.attendees.exclude?(user) && @event.creator != user && @event.invitees.exclude?(user)%>
              <%= link_to invite_event_path(event_id: @event.id, user_id: user.id) do %>
                <div class="block">
                  <p>
                    <span><i class="fas fa-user-plus"></i></span>
                    <%= user.name %>
                  </p>
                </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Create a new event</h1>
					<%= render 'form', event: @event %>
			</div>
		</div>
	</div>
</div>

app/views/events/show.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        <div class="box">
          <div class="level">
            <div class="level-left">
              <div class="level-item">
                <h1 class="title is-4"><%= @event.title %></h1>
              </div>
            </div>
              <% if @event.date >= Date.today %>
                <% if @event.creator == current_user %>
                  <div class="level-right">
                    <div class="level-item">
                      <%= link_to 'Edit Event', edit_event_path, class: "button is-info" %>
                    </div>
                    <div class="level-item">
                      <%= link_to 'Delete Event', event_path, method: :delete, class: "button is-danger" %>
                    </div>
                  </div>
                <% else %>
                  <div class="level-right">
                    <div class="level-item">
                      <% if current_user != @event.creator %>
                        <% if @event.attendees.include?(current_user) %>
                          <%= link_to 'I\'m not going', cancel_event_path, class: "button is-danger" %>
                        <% end %> 
                      <% end %>
                    </div>
                  </div>
                <% end %>
              <% end %>
          </div>
          <div class="block">
            <i class="fas fa-calendar-alt"></i>
            <%= @event.date %>
            <p>Hosted by<br />
            <strong><%= link_to "@" + @event.creator.username, @event.creator %></strong></p>
          </div>

          <div class="block">
            <div class="title is-6">
              Event's details:
            </div>
            <%= @event.description %>
            
          </div>

          <% if @event.attendees.presence %>
            <div class="block">
              <p>
                <div class="title is-6">
                  Attendees
                </div>
                <% @event.attendees.each_with_index do |attendee, index| %>
                  <%= link_to "@" + attendee.username, attendee %>
                  <% if index == @event.attendees.length - 1 %>
                    .
                  <% else %>
                    ,
                    <% end %>
                <% end %>
            </div>
          <% end %>

          <div class="level">
            <div class="level-left">
            <% if current_user == @event.creator %>
              <div class="level-item">
                <%= link_to 'Invite People', invitation_event_path, class: "button is-primary" %>
              </div>
            <% end %>
            </div>
            <div class="level-right">
              <div class="level-item">
                <%= link_to 'Back to Feed', root_path, class: "button is-info" %>
              </div>
            </div>
          </div>
      </div>

      <div class="box">
        <div class="title is-6">
          Add New Comment
        </div>
        <%= render 'comment_form' %>
      </div>

      <% Comment.where(event_id: @event.id).order(:created_at).each do |comment| %>
        <div class="box">
          <div class="block">
            <div class="level">
              <div class="level-left">
                <div class="level-item">
                  <span class="icon"><i class="fas fa-user-alt"></i></span> 
                  <%= link_to "@" + comment.user.username, comment.user %>
                </div>
              </div>
              <div class="level-right">
                <div class="level-item">
                  <%= comment.created_at.localtime.strftime('%Y-%m-%d %H:%M:%S') %>
                  <% if current_user == comment.user %>
                    <%= link_to comment, method: :delete, data: { confirm: "Do you really want to delete your comment?" } do %>
                    <span class="icon"><i class="fas fa-trash-alt is-danger"></i></span>
                  <% end %>
                  <% end %>
                </div>
              </div>
            </div>
              <div class="title is-6">
                
              </div>
                <p>
              <%= comment.body %>
                </p>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css' %>
  </head>

  <body>
    <% if flash[:notice] %>
  		<div class="notification is-primary global-notification">
  			<p class="notice"><%= notice %></p>
  		</div>
  	<% end %>
  	<% if flash[:alert] %>
  		<div class="notification is-danger global-notification">
  			<p class="alert"><%= alert %></p>
  		</div>
  	<% end %>
    <nav class="navbar">
      <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item" do %>
        <h1 class="title is-5">Private Events</h1>
      <% end %>
      </div>

      <div class="navbar-end">
        <div class="navbar-item">
          <div class="field is-grouped">
            <% if user_signed_in? %>
              <p class="control">
                <%= link_to "@" + current_user.username, edit_user_registration_path, class: "button" %>
              </p>
              <p class="control">
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "button" %>
              </p>
            <% else %>

            <p class="control">
              <%= link_to "Sign In", new_user_session_path, class: "button is-info" %>
            </p>
            <p class="control">
              <%= link_to "Sign Up", new_user_registration_path, class: "button is-info" %>
            </p>
            <% end %>
          </div>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        <div class="box">
          <h1 class="title is-3">
            <%= @user.name %>
          </h1>
          <h2 class="title is-5">
            <%= "@" + @user.username %>
          </h2>
          <div class="title is-5">
            Hosted events:
          </div>
          <% @user.events.past.order(:date).each do |event| %>
            <div class="block">
              <s>
                <span class="icon"><i class="fas fa-calendar-alt"></i></span>
                <%= event.date %> - <%= link_to event.title, event %>
              </s>
            </div>
          <% end %>
          <% @user.events.upcoming.order(:date).each do |event| %>
            <div class="block">
              <span class="icon"><i class="fas fa-calendar-alt"></i></span>
              <%= event.date %> - <%= link_to event.title, event %>
            </div>
          <% end %>
          <div class="title is-5">
            Events to attend:
          </div>
          <% Event.all.past.order(:date).each do |event|%>
            <% if event.attendees.include?(@user) %>
              <div class="block">
                <s>
                  <span class="icon"><i class="fas fa-calendar-alt"></i></span>
                  <%= event.date %> - <%= link_to event.title, event %>
                </s>
            </div>
            <% end %>
          <% end %>
          <% Event.all.upcoming.order(:date).each do |event|%>
            <% if event.attendees.include?(@user) %>
              <div class="block">
                <span class="icon"><i class="fas fa-calendar-alt"></i></span>
                <%= event.date %> - <%= link_to event.title, event %>
            </div>
            <% end %>
          <% end %>
          <%= link_to 'Back to Feed', root_path, class: "button is-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>